/**
 * @file Version.h
 * @brief Version information for EEPROM24Cxx.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef EEPROM24CXX_VERSION_STRING
#define EEPROM24CXX_VERSION_STRING "1.0.0"
#endif

#ifndef EEPROM24CXX_BUILD_DATE
#define EEPROM24CXX_BUILD_DATE "unknown"
#endif

#ifndef EEPROM24CXX_BUILD_TIME
#define EEPROM24CXX_BUILD_TIME "unknown"
#endif

#ifndef EEPROM24CXX_BUILD_TIMESTAMP
#define EEPROM24CXX_BUILD_TIMESTAMP "unknown"
#endif

#ifndef EEPROM24CXX_GIT_COMMIT
#define EEPROM24CXX_GIT_COMMIT "unknown"
#endif

#ifndef EEPROM24CXX_GIT_STATUS
#define EEPROM24CXX_GIT_STATUS "unknown"
#endif

#ifndef EEPROM24CXX_VERSION_FULL
#define EEPROM24CXX_VERSION_FULL EEPROM24CXX_VERSION_STRING " (" EEPROM24CXX_GIT_COMMIT ", " EEPROM24CXX_BUILD_TIMESTAMP ", " EEPROM24CXX_GIT_STATUS ")"
#endif

namespace EEPROM24Cxx {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = EEPROM24CXX_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = EEPROM24CXX_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = EEPROM24CXX_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = EEPROM24CXX_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = EEPROM24CXX_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = EEPROM24CXX_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = EEPROM24CXX_VERSION_FULL;

}  // namespace EEPROM24Cxx
